/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QBadge: typeof import('quasar')['QBadge']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QCheckbox: typeof import('quasar')['QCheckbox']
    QDate: typeof import('quasar')['QDate']
    QDialog: typeof import('quasar')['QDialog']
    QFile: typeof import('quasar')['QFile']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QItemSection: typeof import('quasar')['QItemSection']
    QOptionGroup: typeof import('quasar')['QOptionGroup']
    QPopupProxy: typeof import('quasar')['QPopupProxy']
    QRadio: typeof import('quasar')['QRadio']
    QSelect: typeof import('quasar')['QSelect']
    QTab: typeof import('quasar')['QTab']
    QTabPanel: typeof import('quasar')['QTabPanel']
    QTabPanels: typeof import('quasar')['QTabPanels']
    QTabs: typeof import('quasar')['QTabs']
    QTime: typeof import('quasar')['QTime']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SurveyCreateAddOn: typeof import('./src/components/SurveyCreateAddOn.vue')['default']
    SurveyCreateAddOnPage: typeof import('./src/components/SurveyCreateAddOnPage.vue')['default']
    SurveyCreateContents: typeof import('./src/components/SurveyCreateContents.vue')['default']
    SurveyCreateFilter: typeof import('./src/components/SurveyCreateFilter.vue')['default']
    SurveyCreatePreview: typeof import('./src/components/SurveyCreatePreview.vue')['default']
    SurveyCreateQuerys: typeof import('./src/components/SurveyCreateQuerys.vue')['default']
    SurveyCreateQuerysType: typeof import('./src/components/SurveyCreateQuerysType.vue')['default']
    SurveyResult: typeof import('./src/components/SurveyResult.vue')['default']
    SurveyResultTypeMultiChoice: typeof import('./src/components/SurveyResultTypeMultiChoice.vue')['default']
    SurveyResultTypePerDay: typeof import('./src/components/SurveyResultTypePerDay.vue')['default']
    SurveyResultTypePreference: typeof import('./src/components/SurveyResultTypePreference.vue')['default']
    SurveyResultTypePrintModal: typeof import('./src/components/SurveyResultTypePrintModal.vue')['default']
    SurveyResultTypeSingleChoice: typeof import('./src/components/SurveyResultTypeSingleChoice.vue')['default']
    SurveyResultTypeTextType: typeof import('./src/components/SurveyResultTypeTextType.vue')['default']
  }
}
